import { describe, it, expect } from 'vitest';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

describe('layout.tsx', () => {
  it('define metadata esperada', async () => {
    const content = await readFile(join(__dirname, 'layout.tsx'), 'utf8');

    expect(content).toMatch(/title:\s*"Create Next App"/);
    expect(content).toMatch(/description:\s*"Generated by create next app"/);
  });

  it('incluye wrapper html y body', async () => {
    const content = await readFile(join(__dirname, 'layout.tsx'), 'utf8');

    expect(content).toMatch(/<html/);
    expect(content).toMatch(/<body/);
  });
});
