import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

test('layout.tsx define metadata esperada', async () => {
  const content = await readFile(join(__dirname, 'layout.tsx'), 'utf8');

  assert.match(content, /title:\s*"Create Next App"/);
  assert.match(content, /description:\s*"Generated by create next app"/);
});

test('layout.tsx incluye wrapper html y body', async () => {
  const content = await readFile(join(__dirname, 'layout.tsx'), 'utf8');

  assert.match(content, /<html/);
  assert.match(content, /<body/);
});
