import { PrismaUserRepository } from '../repositories/PrismaUserRepository.js';
import { BcryptPasswordHasher } from '../security/BcryptPasswordHasher.js';
import { JwtTokenService } from '../security/JwtTokenService.js';
import { RegisterUser } from '../../application/users/RegisterUser.js';
import { AuthenticateUser } from '../../application/users/AuthenticateUser.js';
import { PrismaAssetRepository } from '../repositories/PrismaAssetRepository.js';
import { CreateAsset } from '../../application/assets/CreateAsset.js';
import { ListAssets } from '../../application/assets/ListAssets.js';
import { GetAsset } from '../../application/assets/GetAsset.js';
export declare const prisma: import("../../../generated/prisma/internal/class.js").PrismaClient<never, import("../../../generated/prisma/internal/prismaNamespace.js").GlobalOmitConfig | undefined, import("@prisma/client/runtime/client").DefaultArgs>;
export declare const userRepository: PrismaUserRepository;
export declare const assetRepository: PrismaAssetRepository;
export declare const passwordHasher: BcryptPasswordHasher;
export declare const tokenService: JwtTokenService;
export declare const registerUser: RegisterUser;
export declare const authenticateUser: AuthenticateUser;
export declare const createAsset: CreateAsset;
export declare const listAssets: ListAssets;
export declare const getAsset: GetAsset;
import { PrismaTicketRepository } from '../repositories/PrismaTicketRepository.js';
import { CreateTicket } from '../../application/tickets/CreateTicket.js';
import { ListTickets } from '../../application/tickets/ListTickets.js';
import { GetTicket } from '../../application/tickets/GetTicket.js';
import { UpdateTicketStatus } from '../../application/tickets/UpdateTicketStatus.js';
export declare const ticketRepository: PrismaTicketRepository;
export declare const createTicket: CreateTicket;
export declare const listTickets: ListTickets;
export declare const getTicket: GetTicket;
export declare const updateTicketStatus: UpdateTicketStatus;
import { PrismaMaintenanceRepository } from '../repositories/PrismaMaintenanceRepository.js';
import { CreateMaintenance } from '../../application/maintenance/CreateMaintenance.js';
import { ListMaintenance } from '../../application/maintenance/ListMaintenance.js';
import { GetMaintenance } from '../../application/maintenance/GetMaintenance.js';
import { UpdateMaintenanceStatus } from '../../application/maintenance/UpdateMaintenanceStatus.js';
export declare const maintenanceRepository: PrismaMaintenanceRepository;
export declare const createMaintenance: CreateMaintenance;
export declare const listMaintenance: ListMaintenance;
export declare const getMaintenance: GetMaintenance;
export declare const updateMaintenanceStatus: UpdateMaintenanceStatus;
//# sourceMappingURL=container.d.ts.map